"use client";
import {useEffect,useState} from "react";
import EmailForm from "./email-form";
import ActivityPulse from "@/components/activity-pulse";
type Metrics={ownerEmail:string;registeredAccounts:number;registeredToday:number;activeToday:number;active30Days:number;lastActivity:number|null;trackingStarted:number|null;generatedAt:number;activity:{day:string;active_accounts:number}[];registrations:{day:string;registrations:number}[]};
export default function Dashboard(){const [data,setData]=useState<Metrics|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch("/api/admin/metrics",{cache:"no-store"});if(r.status===401){location.assign("/login");return;}if(r.status===403){setData(null);throw Error("This dashboard is available only to the owner.");}if(!r.ok)throw Error("Could not load usage. Try again.");setData(await r.json() as Metrics);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not connect.");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 const days=Array.from({length:30},(_,i)=>new Date((data?.generatedAt??Date.now())-i*86400000).toISOString().slice(0,10));
 return <main className="admin-dashboard"><ActivityPulse/><a href="/">← Your calendar</a><div className="heading"><div><div className="eyebrow">OWNER ONLY</div><h1>Daybell usage</h1><p>Account counts and recent activity, without private calendar details.</p></div><button className="primary" onClick={()=>void load()} disabled={busy}>{busy?"Refreshing…":"Refresh"}</button></div>{error&&<p role="alert">{error}</p>}{data&&<><section className="admin-cards">{[["Registered accounts",data.registeredAccounts],["New accounts today",data.registeredToday],["Active today",data.activeToday],["Active in 30 days",data.active30Days]].map(([label,value])=><article className="panel" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel admin-details"><h2>Recent activity</h2><p>Last recorded use: {data.lastActivity?new Date(data.lastActivity).toLocaleString():"No activity recorded yet"}.</p><p>Tracking began: {data.trackingStarted?new Date(data.trackingStarted).toLocaleString():"Not available"}. Updated: {new Date(data.generatedAt).toLocaleTimeString()}.</p><p>Active means a signed-in account opened or interacted with a visible app. Background calendar polling does not count. Counts include the owner, use UTC dates, and do not represent people online right now. Deleted accounts are removed from these statistics.</p><p>Activity before tracking began is unavailable. Older activity records are cleared during new activity, keeping a 90-day history window; no calendar titles, passwords, IP addresses or device identifiers are stored in these usage records.</p><table><thead><tr><th>Date (UTC)</th><th>Active accounts</th><th>New accounts still registered</th></tr></thead><tbody>{days.map(day=><tr key={day}><td>{day}</td><td>{data.trackingStarted&&day<new Date(data.trackingStarted).toISOString().slice(0,10)?"Not tracked":data.activity.find(x=>x.day===day)?.active_accounts??0}</td><td>{data.registrations.find(x=>x.day===day)?.registrations??0}</td></tr>)}</tbody></table></section><EmailForm current={data.ownerEmail} onChanged={()=>void load()}/></>}</main>;
}
